1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [19]:
import numpy as np
a = np.array(range(1,11))
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [20]:
a = np.zeros((3, 3), dtype = int)
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [21]:
import random
a = np.random.randint(1, 11, (5, 5))
a

array([[ 4,  6,  3, 10,  6],
       [10,  5,  5, 10,  6],
       [ 5,  9,  8,  1,  4],
       [ 7,  6,  1,  7,  7],
       [ 4,  6,  2,  3, 10]])

4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.


In [22]:
a = np.random.randint(0,2, (4,4), dtype = int)
a

array([[0, 0, 0, 1],
       [0, 1, 1, 0],
       [1, 1, 0, 0],
       [0, 1, 1, 0]])

5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.


In [23]:
a = np.random.randint (1, 11, 5, dtype = int)
b = np.random.randint (1, 11, 5, dtype = int)
print(a)
print(b)
print(f"Додавання - {a+b}")
print(f"Віднімання - {a-b}")
print(f"Множення - {a*b}")

[ 7  2  7  6 10]
[5 4 3 7 1]
Додавання - [12  6 10 13 11]
Віднімання - [ 2 -2  4 -1  9]
Множення - [35  8 21 42 10]


6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.


In [24]:
a = np.random.rand(7)
b = np.random.rand(7)
print(a)
print(b)
c = np.dot(a, b)
print(c)

[0.14898135 0.1980994  0.01742009 0.36975273 0.12728607 0.83385675
 0.27883073]
[0.6123159  0.86099612 0.04106005 0.78456756 0.29002323 0.99588101
 0.41304085]
1.5351042273439608


7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.


In [25]:
a = np.random.randint(1,11, (2,2))
b = np.random.randint(1,11, (2,3))
print(a)       
print(b)  
c = np.dot(a, b)
print(c)

[[5 2]
 [2 6]]
[[9 3 8]
 [8 3 8]]
[[61 21 56]
 [66 24 64]]


8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.


In [26]:
a = np.random.randint(1, 11, (3, 3))
print(a)
a_inv = np.linalg.inv(a)
print(a_inv)

[[ 2 10  5]
 [ 7  3  2]
 [ 4  6 10]]
[[-0.04147465  0.16129032 -0.01152074]
 [ 0.14285714  0.         -0.07142857]
 [-0.06912442 -0.06451613  0.14746544]]


9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.


In [27]:
a = np.random.randint(0,2, (4,4))
print(a)
a_trans = a.T
print(a_trans)

[[1 0 0 0]
 [1 0 0 1]
 [0 1 0 1]
 [0 0 0 0]]
[[1 1 0 0]
 [0 0 1 0]
 [0 0 0 0]
 [0 1 1 0]]


10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.


In [28]:
a = np.random.randint(1,11, (3,4))
b = np.random.randint(1, 11, 4)
c = np.dot(a, b)
print(a)
print(b)
print(c)

[[ 8  5  2  4]
 [ 1  8  8  3]
 [10 10  9  8]]
[ 3  9 10  2]
[ 97 161 226]


11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.


In [29]:
a = np.random.randint(0, 2, (2,3))
b = np.random.randint(0, 2, 3)
c = np.dot(a, b)
print(a)
print(b)
print(c)

[[0 0 1]
 [1 0 0]]
[1 1 0]
[0 1]


12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.


In [30]:
a = np.random.randint(1,11, (2, 2))
b = np.random.randint(1, 11, (2, 2))
c = a * b
print(a)
print(b)
print(c)

[[8 4]
 [3 5]]
[[7 4]
 [3 9]]
[[56 16]
 [ 9 45]]


13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.


In [31]:
a = np.random.randint(1,11, (2, 2))
b = np.random.randint(1, 11, (2, 2))
c = np.dot (a,b)
print(a)
print(b)
print(c)

[[8 7]
 [3 4]]
[[1 3]
 [5 1]]
[[43 31]
 [23 13]]


14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.


In [32]:
a = np.random.randint(1,101, (5, 5))
print(a)
print(a.sum())

[[75 99 58 97  4]
 [55 37 40 44 38]
 [ 2 95 10  4 14]
 [38 93 94 77 50]
 [49 24 92 67 98]]
1354


15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.


In [33]:
a = np.random.randint(1,11, (4, 4))
b = np.random.randint(1, 11, (4, 4))
c = a - b
print(a)
print(b)
print(c)

[[ 3  7  2  3]
 [ 5  8 10 10]
 [ 6  5  4  5]
 [ 2  6  4  5]]
[[ 7  1  5  3]
 [ 6  6  3  2]
 [ 7  9  6  2]
 [ 6  1  6 10]]
[[-4  6 -3  0]
 [-1  2  7  8]
 [-1 -4 -2  3]
 [-4  5 -2 -5]]


16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.


In [34]:
a = np.random.randint(0,2, (3, 3))
b = a.sum(axis=1)
print(a)
print(b)

[[0 0 0]
 [0 0 0]
 [1 1 0]]
[0 0 2]


17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.


In [35]:
a = np.random.randint(1, 11, (3, 4))
b = a **2
print(a)
print(b)

[[ 4  3  6  7]
 [ 8  1  3 10]
 [ 6  2  4  6]]
[[ 16   9  36  49]
 [ 64   1   9 100]
 [ 36   4  16  36]]


18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.


In [36]:
a = np.random.randint(1, 51, 4)
b = a**0.5
print (a)
print (b)

[25 11 50 50]
[5.         3.31662479 7.07106781 7.07106781]
